package main

import (
	"golang-tutorial/channels"
)

func main() {
	//variables.RunVariables()
	//types.RunTypes()
	//constants.RunConstants()
	//functions.RunFunctions()
	//packages.RunPackages()
	//conditionals.RunConditionals()
	//loops.RunLoops()
	//switch_statement.RunSwitchStatement()
	//arrays.RunArrays()
	//slices.RunSlices()
	//variadic_functions.RunVariadicFunctions()
	//maps.RunMaps()
	//strings.RunStrings()
	//pointers.RunPointers()
	//structures.RunStructures()
	//methods.RunMethods()
	//interfaces.RunInterfaces1()
	//interfaces.RunInterfaces2()
	//concurrency.RunConcurrency()
	//goroutines.RunGoroutines()
	channels.RunChannels()
	//goroutines.RunBufferedPools()
	//channels.RunWorkerPoolsDemo()
	//channels.RunSelect()
	//mutexes.RunMutexes()
	//oop.RunInheritance()
	//oop.RunPolymorphism()
	//error_handling.RunErrorHandling()
	//error_handling.RunPanicAndRecover()
	//error_handling.RunPanicAndRecover2()
	//first_class.RunFirstClassFunctions()
	//reflection.RunReflection()
	//exercises.ReadFiles()
	//exercises.WriteFiles()
}