package main

import "golang-tutorial/reflection"

func main() {
	//variables.RunVariables()
	//types.RunTypes()
	//constants.RunConstants()
	//functions.RunFunctions()
	//packages.RunPackages()
	//conditionals.RunConditionals()
	//loops.RunLoops()
	//switch_statement.RunSwitchStatement()
	//arrays.RunArrays()
	//slices.RunSlices()
	//variadic_functions.RunVariadicFunctions()
	//maps.RunMaps()
	//strings.RunStrings()
	//pointers.RunPointers()
	//structures.RunStructures()
	//methods.RunMethods()
	//interfaces.RunInterfaces1()
	//interfaces.RunInterfaces2()
	//concurrency.RunConcurrency()
	//concurrency.RunGoroutines()
	//concurrency.RunChannels()
	//concurrency.RunBufferedPools()
	//concurrency.RunWorkerPoolsDemo()
	//concurrency.RunSelect()
	//concurrency.RunMutexes()
	//oop.RunClasses()
	//oop.RunInheritance()
	//oop.RunPolymorphism()
	//defers.RunDefers()
	//error_handling.RunErrorHandling()
	//error_handling.RunPanicAndRecover()
	//error_handling.RunPanicAndRecover2()
	//first_class.RunFirstClassFunctions()
	reflection.RunReflection()
	//exercises.ReadFiles()
	//exercises.WriteFiles()
}